Read configuration from a .env file (or environment variables)
zikani03/calendago pull request #4
Opened 2022-09-03 21:15 UTC by TgkCapture

Fixes #1

2022-09-03 21:16 UTC, TgkCapture commented
Seem to be missing something on here, Please check and advise. :)

2022-09-06 19:17 UTC, zikani03 requested changes

2022-09-06 19:17 UTC, zikani03 commented on main.go
> +	err = os.MkdirAll(os.Getenv("UP_IMAGE_PATH "), os.ModePerm)
The environment variable should be `CALENDAGO_WORK_DIR`

2022-09-08 17:10 UTC, TgkCapture reviewed
Thanks :)

2022-09-08 17:10 UTC, merged