changes to the index page
zikani03/calendago pull request #9
Opened 2022-12-19 20:00 UTC by kennedylinzie

cosmetic changes to the index page.

2022-12-19 20:03 UTC, kennedylinzie commented
![change](https://user-images.githubusercontent.com/17104217/208510363-586dfb83-bde9-4a1c-9b18-b3ac88775f19.jpg)

2022-12-20 05:52 UTC, zikani03 requested changes
Looks good. Just fix the form method/action

2022-12-20 05:52 UTC, zikani03 commented on static/index.html
> +          <form>
Change the form to use a post to the "/calendar" endpoint

`<form method="post" action="/calendar" enctype="multipart/form-data">`

2022-12-20 09:03 UTC, kennedylinzie commented
changes made ,wonder how I missed that haha

2022-12-20 10:45 UTC, zikani03 approved these changes

2022-12-20 10:45 UTC, merged